name: Azure Web App DeployY

on: 
  push:
    branches: 
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        name: build

        steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4.0.2
        
        - name: 'npm install and test'
          run: | 
            npm install
            npm test
        
        - name: Archive production artifacts
          uses: actions/upload-artifact@v2
          with: 
            name: node-project-artifact
            path: | 
              ./
              |./nome_modules
    
    depoy:
        name: Deploy to Azure Web App
        runs-on: ubuntu-latest
        needs: build
    
        steps:
        - name: Download artifact
          uses: actions/download-artifact@v2
          with: 
            name: node-project-artifact
            path: ./
        
        - name: 'npm install'
          run: | 
            npm install
        
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with: 
            creds: ${{ secrets.AZURE.CREDENTIALS }}
        
        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'github-actions-demo-dfoggi'
            slot-name: 'production'
